---
org: osomonodev
app: trading-helper
service: trading-helper
custom:
  pythonRequirements:
    dockerizePip: true
plugins:
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  timeout: 10
  role: arn:aws:iam::878586529059:role/serverlessLabs
  memorySize: 512
resources:
  Resources:
    RDSCluster:
          Type: AWS::RDS::DBCluster
          Properties:
              Engine: aurora-mysql
              DatabaseName: tradinghelper
              EngineVersion: 5.7.mysql_aurora.2.12.1
              MasterUsername: serviceuser
              MasterUserPassword: myawesomepassword
              PreferredBackupWindow: 02:00-03:00
              PreferredMaintenanceWindow: mon:03:00-mon:04:00
    RDSInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        Engine: aurora-mysql
        DBClusterIdentifier:
          Ref: RDSCluster
        DBInstanceClass: "db.t3.small"

functions:
  first_function:
    handler: src.handler.test_function
    events:
      - http:
          path: test
          method: get
