service: trading-helper

provider:
  name: google
  stage: dev
  runtime: python39
  region: us-central1
  project: 	trading-helper-419411
  credentials: ${env:CREDENTIALS_PATH}
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  # credentials: ~/.gcloud/keyfile.json

frameworkVersion: '3'
plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - infra/**
    - app.py
    - node_modules/**
    - .gitignore
    - .git/**
    - .github/**
    - .pre-commit-config.yaml

functions:
  first:
    handler: get_user
    events:
      - http: true
  # NOTE: the following uses an "event" event (pubSub event in this case).
  # Please create the corresponding resources in the Google Cloud
  # before deploying this service through Serverless
  #second:
  #  handler: event
  #  events:
  #    - event:
  #        eventType: providers/cloud.pubsub/eventTypes/topic.publish
  #        resource: projects/*/topics/my-topic
# you can define resources, templates etc. the same way you would in a
# Google Cloud deployment configuration
