name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      run: npm install
    - name: Decrypt secret
      run: ./.github/scripts/decrypt_secret.sh
      env:
        DECRYPTION_KEY: ${{ secrets.DECRYPTION_KEY }}
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        CREDENTIALS_PATH: /github/workspace/secrets/credentials.json
